# Generated by Django 2.2.12 on 2020-04-12 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_participation',
            field=models.DateTimeField(null=True),
        ),
    ]
